REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM shopsuser;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM shopsuser;
DROP USER shopsuser;

DO
$body$
BEGIN
   IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_user WHERE usename = 'shopsuser') THEN
      CREATE USER shopsuser WITH PASSWORD '123123';
   END IF;
END
$body$
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO shopsuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shopsuser;